---
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        informational: false
    patch:
      default:
        target: auto
        informational: true

comment: false
