# LTI Data-Driven MPC Parameters
# Based on the Data-Driven MPC implementation example for the control of a
# linearized four-tank system from Section V of the paper:
# [1] J. Berberich, J. Köhler, M. A. Müller and F. Allgöwer, "Data-Driven
#     Model Predictive Control With Stability and Robustness Guarantees," in
#     IEEE Transactions on Automatic Control, vol. 66, no. 4, pp. 1702-1717,
#     April 2021, doi: 10.1109/TAC.2020.3000182.

lti_data_driven_mpc_params:
  n: 4  # Estimated system order

  N: 400  # Initial input-output trajectory length
  L: 30  # Prediction horizon
  Q_scalar: 3  # Scalar multiplier for the output weighting matrix Q
  R_scalar: 1.0e-4  # Scalar multiplier for the input weighting matrix R

  epsilon_bar: 0.002  # Estimated upper bound of system measurement noise
  lambda_sigma: 1000  # Regularization parameter for the slack variable
  lambda_alpha_epsilon_bar: 0.1  # Regularization parameter for alpha

  # Range of the persistently exciting input u_d
  # Note: Each input must have an associated vector of ranges [min, max]
  u_d_range:
    - [-1, 1]
    - [-1, 1]

  slack_var_constraint_type: 0  # Slack variable constraint type:
                                # - 0 = None → Omit explicit constraint. The
                                #              slack variable constraint is
                                #              implicitly satisfied (Remark 3
                                #              of [1]).
                                # - 1 = Convex → Convex slack variable
                                #                constraint (Remark 3 of [1]).
                                # - 2 = Non-Convex → Non-Convex slack variable
                                #                    constraint (Equation (6d)
                                #                    of [1]).

  controller_type: 1  # Data-Driven MPC controller type:
                      # - 0 → Nominal Data-Driven MPC
                      # - 1 → Robust Data-Driven MPC

  u_s: [1, 1]  # Control input setpoint
  y_s: [0.65, 0.77]  # System output setpoint

  n_n_mpc_step: true  # Enable n-Step Data-Driven MPC:
                      # - true = n-Step Data-Driven MPC
                      # - false = 1-Step Data-Driven MPC